### ISSUE TITLE
Run into an error when authorizing the app

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Bluemix/openwhisk-slackapp#7]
Everything is looking good until I click the "Authorize" button... at which point I get this error:

![image](https://user-images.githubusercontent.com/9341504/31207217-c67973e2-a931-11e7-8e7e-bc79f154a518.png)

Any idea how to troubleshoot? Thanks!

**Comment by l2fprod** [comment]
@bobbinrobyn 

I found a typo in the readme in https://github.com/IBM-Bluemix/openwhisk-slackapp/blob/master/README.md#set-the-callback-url-for-authentication, it said "slackapp-registry" instead of "slackapp-register" for the action name in the Redirect URL. It could be the issue. Can you check what you have under OAuth and Permissions
